### PR TITLE
add NPO_2001 to NPO_2006

### PR DESCRIPTION
**Pull request by JKChang2015**
added 
biopolymer nanoparticle NPO_2001
carbon black nanoparticle NPO_2002
alloy nanoparticle NPO_2003
nanobin NPO_2004
nanolipogel NPO_2005
solubility in organic solvents NPO_2006

### CODE REVIEW

**Comment by JKChang2015** [comment]
@egonw Could you please double check these terms and merge them. Thank you.
More details: https://docs.google.com/spreadsheets/d/1rZOsAID7dBRziOXbqVbgUnNP6TGLDxDI9CTLrFcsVAM/edit?usp=sharing

**Comment by egonw** [comment]
HI @JKChang2015, I cannot review this, as the whole file is turned upside down :(

**Comment by JKChang2015** [comment]
Hi @egonw , I think those terms have been successful merged to eNM ontology after Maastricht hackathon in February.  Here is the link to the working spreadsheet:
https://docs.google.com/spreadsheets/d/1rZOsAID7dBRziOXbqVbgUnNP6TGLDxDI9CTLrFcsVAM/edit?usp=sharing

**Comment by egonw** [comment]
OK, then I'll close this for now. We need a larger merge event anyway, to move stuff from ENM back into NPO.

**Pull request closed without merging**
